services:
  app-backend:
    build:
      context: ./backend
    image: app-backend
    container_name: app-backend
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - user-data:/app/user_data
    env_file: backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    command: [ "--config", "/etc/mongo/mongod.conf" ]
    env_file: mongo.env
    networks:
      - app-network


  app-frontend:
    build:
      context: ./frontend
    depends_on:
      - app-backend
    image: app-frontend
    container_name: app-frontend
    restart: always
    ports:
      - "3001:8000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  user-data:
  mongo-data: